### ISSUE TITLE
downloadECLS_K, then cannot find data.

### ISSUE THREAD

**Issue by pdbailey0** [American-Institutes-for-Research/EdSurvey#1]
A user ran the following code and could not understand the error:

![image](https://user-images.githubusercontent.com/14575300/123813456-87469a80-d8ba-11eb-925c-3b399a01d575.png)

Writing, "As you can see from the above codes, I tried different ways to call or read the data using different paths/locations but unfortunately I could not read the data."

**Comment by pdbailey0** [comment]
I would first look in the path to see if you can find `childK5p.dat`. Where you find that file is where to point EdSurvey.

In the short run, I would change the download call to `root="C:/"` so that the call is

```r
downloadECLS_K(years=2011, root="C:/", cache=FALSE)
```

EdSurvey makes the folders `\ECLS_K\2011` in the root, so I think you will find the data in `C:\ECLS_K\2011\ECLS_K\2011\`. Since you have already downloaded the data, I would just move it to a location that is convenient for you and then point `readECLS_K2011` at that folder.

**Comment by rlbresearcher** [comment]
Hi Paul, 

So I did what you suggested: to use the code 
**downloadECLS_K(years=2011, root="C:/", cache=FALSE)** and checked if the file **"childK5p"** is located in that folder. Yes this file is in that "C:/" folder. I wish I could attach an image copy. 

However, I'm still getting that error message when reading the data. I do not know if "childK5p.dat" (which you suggested) is different from "ChildK5p" (which is shown in the folder: "C:/"?

Also, once we have downloaded the ECLS_K, do we need to unzip the file or leave it as is? 

Thanks,
Rommel

**Comment by rlbresearcher** [comment]
Hi Paul,

I don't know what the issue is with reading the file. I followed your
recommendation but still didn't work. I even tried different ways but to no
avail, I'm still getting the same error message. Please see attached my
documentation of the processes. I thought I already knew how to read files
in R, but don't know what's the problem.

Let me know.

Thanks,
Rommel

**Comment by pdbailey0** [comment]
I'm confused, is this an email or a comment that was deleted?

**Comment by rlbresearcher** [comment]
Hi Paul,

I'm resending my email with my comments. Initially I sent the email with
the comment as an attachment (containing a documentation of the issue) but
it did not appear in the github so I deleted it. So here's the email again.

***************************************************************************************************************************************
1) All the files are saved in USB Drive (H:) jump drive including the
downloaded ECLS_K .
[image: image.png]

2) Inside the ECLS_K folder, you will see the ECLS_K data:

[image: image.png]

3) Following your suggestions, please see below:

[image: image.png]
You can see that the directory is "*H:/Research
Agenda/ecls/ECLS_K/2011/ChildK5p*" which is the same as the text inside the
red box.


4) Then read the ECLS_K data using your codes:
[image: image.png]

*But got an error message:*
[image: image.png]

5) I even tried another option using the code (see below):

        dir <- "H:/Research Agenda/ecls/ECLS_K/2011/ChildK5p"
       dirname(dir)
      ecls2011 <- readECLS_K2011(dirname(dir), filename = "ChildK5p.dat")

 *But still got an error message: *

[image: image.png]

Let me know what you think.

Thanks,
Rommel

**Comment by pdbailey0** [comment]
Hi Rommel, I don't see the images. I usually copy and paste them one by one. You can edit your comments by selecting the three dots in the top right and then selecting "Edit"

![image](https://user-images.githubusercontent.com/14575300/124168016-31185980-da6a-11eb-80a3-aa821baf11c3.png)

**Comment by rlbresearcher** [comment]
Hi Paul,

I copied and pasted the images already but they do not show until you
click the links.

Thanks,
Rommel

**Comment by pdbailey0** [comment]
@rlbresearcher my recomendation was going to be that you did what you say you did in the end. I'll note the image does not seem to reflect the code you shared.

try this:
```r
dir <- "H:/Research Agenda/ecls/ECLS_K/2011/"
ecls2011 <- readECLS_K2011(dir, filename = "ChildK5p.dat")
```

if that does not work, please show the results of this:
```r
dir <- "H:/Research Agenda/ecls/ECLS_K/2011/"
list.files(dir)
```

**Comment by pdbailey0** [comment]
@rlbresearcher I just looked at your final error again. IT reads, "Cannot find specified layout file 'H:/Research Agenda/ecls/ECLS_K/ChildK5p/ECLSK2011_K5PUF.sps' in path 'H:/Research Agenda/ecls/ECLS_K/ChildK5p/'." Have you looked at that path to see if the file is there?

**Comment by rlbresearcher** [comment]
Hi Paul,

I found the error that needs to be corrected. I will update you as soon as
the datafile has been read. It's a large file and my computer is slow and
probably will take longer than it should to read the data.

Thanks!
