### ISSUE TITLE
ECLS-K data and weights 

### ISSUE THREAD

**Issue by zq8890** [American-Institutes-for-Research/EdSurvey#11]
When using ECLS-K data with EdSurvey package: 
1. should child level weights be scaled in anyway for use with "long" data and/or mixed models? 
2. when pulling in data, is it acceptable to only run analyses on a portion of data relevant for analyses? (i.e. only those with complete BMI data at all waves). In other software packages, normally the full dataset is used, but the PSU/Strata and weight variables only include the relevant observations.

**Comment by pdbailey0** [comment]
Thank you for your question. Since this is a question specific to ECLS data, we recommend contacting Jill McCarroll, the ECLS study director, at Jill.McCarroll@ed.gov. The ECLS team will be able to respond directly to your question about weights.

**Comment by pdbailey0** [comment]
I'm going to close this because this discussion seems to be complete.
