### ISSUE TITLE
R CMD check warnings

### ISSUE THREAD

**Issue by coatless** [American-Institutes-for-Research/EdSurvey#12]
From the CI run of R CMD check, there are a few warnings / errors. 

Full results can be found here: 

https://github.com/American-Institutes-for-Research/EdSurvey/runs/3757157906#step:6:1058

<details>
<summary> result from R CMD check </summary>.

❯ checking package subdirectories ... WARNING
  Problems with news in ‘inst/NEWS.Rd’:
    inst/NEWS.Rd:14: unexpected section header '\section'
    inst/NEWS.Rd:49: unexpected section header '\section'
    inst/NEWS.Rd:92: unexpected section header '\section'
    inst/NEWS.Rd:142: unexpected section header '\section'
    inst/NEWS.Rd:174: unexpected section header '\section'
    inst/NEWS.Rd:207: unexpected section header '\section'
    inst/NEWS.Rd:224: unexpected section header '\section'
    inst/NEWS.Rd:275: unexpected section header '\section'
    inst/NEWS.Rd:336: unexpected section header '\section'
    inst/NEWS.Rd:345: unexpected END_OF_INPUT '
    '

❯ checking for code/documentation mismatches ... WARNING
  Functions or methods with usage in documentation object 'readNLS72' but not in code:
    ‘readNLS72’
  
  Codoc mismatches from documentation object 'SD':
  SD
    Code: function(data, variable, weightVar = NULL, jrrIMax = 1,
                   varMethod = "jackknife", omittedLevels = TRUE,
                   defaultConditions = TRUE, recode = NULL, targetLevel =
                   NULL, jkSumMultiplier = getAttributes(data,
                   "jkSumMultiplier"), returnVarEstInputs = FALSE)
    Docs: function(data, variable, weightVar = NULL, jrrIMax = 1,
                   varMethod = "jackknife", omittedLevels = TRUE,
                   defaultConditions = TRUE, recode = NULL, targetLevel =
                   NULL, jkSumMultiplier = 1, returnVarEstInputs = FALSE)
    Mismatches in argument default values:
      Name: 'jkSumMultiplier' Code: getAttributes(data, "jkSumMultiplier") Docs: 1

❯ checking top-level files ... NOTE
  Non-standard files/directories found at top level:
    ‘README.html’ ‘README.Rmd’

❯ checking R code for possible problems ... NOTE
  processCountryPIAAC: no visible global function definition for
    ‘write.table’
    (/Users/runner/work/EdSurvey/EdSurvey/check/EdSurvey.Rcheck/00_pkg_src/EdSurvey/R/readPIAAC.R:298)
  processMergeTxt: no visible global function definition for
    ‘write.table’
    (/Users/runner/work/EdSurvey/EdSurvey/check/EdSurvey.Rcheck/00_pkg_src/EdSurvey/R/readPISA.R:1027-1029)
  processPISA2015: no visible global function definition for
    ‘write.table’
    (/Users/runner/work/EdSurvey/EdSurvey/check/EdSurvey.Rcheck/00_pkg_src/EdSurvey/R/readPISA.R:1325)
  processPISA2018_FIN: no visible global function definition for
    ‘write.table’
    (/Users/runner/work/EdSurvey/EdSurvey/check/EdSurvey.Rcheck/00_pkg_src/EdSurvey/R/readPISA.R:1745)
  writeFWF: no visible global function definition for ‘write.table’
    (/Users/runner/work/EdSurvey/EdSurvey/check/EdSurvey.Rcheck/00_pkg_src/EdSurvey/R/readTALIS.R:482-484)
  Undefined global functions or variables:
    write.table
  Consider adding
    importFrom("utils", "write.table")
  to your NAMESPACE file.

</details>

**Comment by pdbailey0** [comment]
fixed by https://github.com/American-Institutes-for-Research/EdSurvey/pull/13
