### ISSUE TITLE
RFE: EdSurvey enhancement suggestion

### ISSUE THREAD

**Issue by niguarino** [American-Institutes-for-Research/EdSurvey#18]
I would love if EdSurvey could expand the regression options for studying correlates with categorical outcomes. Right now, glm.sdf offers the opportunity to look at binary outcomes via logit and probit. I think it would be great if it could be expanded to multinomial outcomes so I can calculate relative risk ratios for non-dichotomous categorical data. The way I'm thinking of addressing this at the moment is switching to Stata, but it would be great if I could do this in EdSurvey instead. Thanks for listening to this suggestion.

**Comment by pdbailey0** [comment]
@niguarino tanks for the request. Can you help us with a use case and what statistics you would like to see?

**Comment by niguarino** [comment]
@pdbailey0 yes, I'd be happy to help. Generally, I am looking to see odds ratios with a 95% confidence interval, as well as p-values of the relative risk ratios. In my case, I am looking to run a nominal logistic regression. Please let me know what other information I can provide. May I email you the specifics of the use case? I'd rather not post my project specifics publically.

**Comment by pdbailey0** [comment]
NCES has decided this is not a funding priority for EdSurvey but would happily entertain submitted code consistent with our [code contribution policy](https://github.com/American-Institutes-for-Research/EdSurvey#contributions).
