### ISSUE TITLE
School level correlations between mathematics and science (TIMSS)

### ISSUE THREAD

**Issue by vejUA** [American-Institutes-for-Research/EdSurvey#23]
I would like to examine whether there is a correlation between average achievement in mathematics and science (and the subdomains) at the school level, based on the TIMSS 2019 data. I would like to investigate whether the correlation between mathematics and science achievement scores of students differ between schools. 

If I understand the instructions from the PISA Data Analysis Manual (OECD, 2009) correctly, I could take the following steps:
1° Calculate the average achievement score for mathematics and science per school for each plausible value
2° Calculate the correlation between the scores for mathematics and science at school level for each plausible value separately
3° Take the average of the correlations

But by doing so I don't take the weights into account and I don't precisely know how to calculate the standard error. 

Is there a possibility in EdSurvey to conduct these analyses and/or which steps should I take?

Thanks in advance

Reference: OECD. (2009). PISA Data Analysis Manual: SPSS, Second Edition. https://doi.org/10.1787/19963777 (p. 124-127)

**Comment by pdbailey0** [comment]
On the [AIR EdSurvey website](https://www.air.org/project/nces-data-r-project-edsurvey) you can find several how to manuals. One regards [using TIMSS data in EdSurvey](https://www.air.org/sites/default/files/edsurvey-TIMSS-pdf.pdf).

One section of that regards weighted correlations.

When EdSurvey analyzes the weighted correlations between two constructs it will not only estimate the survey standard error but also the standard error associated with the uncertainty associated with the construct scores.

I hope that answers your question! Feel free to reopen this if it does not.

Best,
Paul

**Comment by vejUA** [comment]
Thank you for the quick reply and the links to the walk troughs. 
The problem I am facing is that I want to check the correlation between the maths and science scores at the school level. When I aggregate the individual student scores to the school level, I cannot use the cor.sdf function anymore. The script below shows what I would like to do, but without taking the weights etc into account. The figure represents the problem visually.


``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2)      
library(EdSurvey)
#> Loading required package: car
#> Loading required package: carData
#> 
#> Attaching package: 'car'
#> The following object is masked from 'package:dplyr':
#> 
#>     recode
#> Loading required package: lfactors
#> lfactors v1.0.4
#> EdSurvey v2.7.1
#> 
#> Attaching package: 'EdSurvey'
#> The following objects are masked from 'package:base':
#> 
#>     cbind, rbind

TIMSS_Data <- readTIMSS(path = "D:/TIMSS/Data/T19_G4_SPSS Data",
                 gradeLvl="4",
                 countries = "bfl")
#> Found cached data for country code "bfl".

Data <- EdSurvey::getData(data = TIMSS_Data, varnames = c("idstud","idschool",
                                                       "mmat", "ssci",
                                                       "mnum","mgeo","mdat",
                                                       "slif","sphy","sear",
                                                       "mkno","mapp","mrea","skno","sapp","srea",
                                                       "totwgt","schwgt"),
                              omittedLevels = FALSE, addAttributes = TRUE)

Data2 <- Data %>% 
  group_by(idschool) %>% 
  summarise(MathPV1=mean(asmmat01),
         MathPV2=mean(asmmat02),
         MathPV3=mean(asmmat03),
         MathPV4=mean(asmmat04),
         MathPV5=mean(asmmat05),
         SciPV1=mean(asssci01),
         SciPV2=mean(asssci02),
         SciPV3=mean(asssci03),
         SciPV4=mean(asssci04),
         SciPV5=mean(asssci05))

( cor(Data2$MathPV1,Data2$SciPV1)+
  cor(Data2$MathPV2,Data2$SciPV2)+
  cor(Data2$MathPV3,Data2$SciPV3)+
  cor(Data2$MathPV4,Data2$SciPV4)+
  cor(Data2$MathPV5,Data2$SciPV5)
)/5
#> [1] 0.9457201
```
![Question GitHub drawio](https://user-images.githubusercontent.com/87800571/141943617-dcf0a06c-e878-4124-8b0c-89f4f7bd535d.png)

**Comment by pdbailey0** [comment]
@vejUA Here’s some guidance as to how to analyze TIMSS data at the school level:
 
When analyzing school context data from the TIMSS International Database, it is preferable that they be analyzed to make inferences about students attending schools with a given characteristic, rather than about schools of a given characteristic. Analyzing school context data with student achievement requires that the school context data files be merged with the student context data files to retrieve the achievement scores and required sample design variables.
