### ISSUE TITLE
RFE: Using gap in non-NAEP analyses

### ISSUE THREAD

**Issue by niguarino** [American-Institutes-for-Research/EdSurvey#24]
I'm wondering if you would recommend using the command gap in non-NAEP analyses, such as one of the NCES longitudinal studies. For example, I would like to check whether students within a certain category raised their achievement scores between two time points. I am not sure how to do this within EdSurvey. It seems observations would need to be clustered, and I'm not sure how to achieve this at the same time as applying the weights. Thanks for any advice you can provide.

**Comment by pdbailey0** [comment]
@niguarino, yes the gap function would work for that. It compares two groups and accounts for the clustered nature of the survey. It seems you may have additional questions inside of the larger one you shared above, so feel free to reopen this issue with specifics.

**Comment by niguarino** [comment]
@pdbailey0, thank you. I am more interested in using `gap()` to compare within-category differences across years than I am in comparing across two categories. For example, I would like to know in the HSLS whether overall GPA was higher for students in the first follow-up versus the base year within SES quintiles. In this case, I don't wish to compare across categories but only within categories. It seems that `gap()` may not be appropriate for this analysis, but I'm not sure. I have questions about how to set up the data in order to use `gap()`. (The NAEP documentation uses randomly generated data, so I don't quite understand the data structure.) I don't want to ask those questions unless I really should be using `gap()`. Thanks again.

**Comment by pdbailey0** [comment]
Yes, this is not addressed by `gap()` I'm reopening.

**Comment by pdbailey0** [comment]
NCES has decided this is not a funding priority for EdSurvey but would happily entertain submitted code consistent with our [code contribution policy](https://github.com/American-Institutes-for-Research/EdSurvey#contributions).
