### ISSUE TITLE
RFE: paired t-test across subscales

### ISSUE THREAD

**Issue by pdbailey0** [American-Institutes-for-Research/EdSurvey#25]
I'm documenting here that Christian Christrup Kjeldsen requested paired t-test of the mean difference between subscales. e.g., do students score significantly higher on one subscale than another?

**Comment by tzhangumd** [comment]
Just read this request. I wonder this is a valid comparison? Aren't they different subconstruct and measured by different items? How does this differ from comparing a reading scale against a math scale? ...

**Comment by pdbailey0** [comment]
Before scaling, I think it is. After scaling, I'm less sure. I'll ask Christian.

**Comment by pdbailey0** [comment]
NCES has decided this is not a funding priority for EdSurvey but would happily entertain submitted code consistent with our [code contribution policy](https://github.com/American-Institutes-for-Research/EdSurvey#contributions).
