### ISSUE TITLE
Missing fr2 file for readNAEP

### ISSUE THREAD

**Issue by TKelleyKemple** [American-Institutes-for-Research/EdSurvey#27]
I'm attempting to use the EdSurvey package on NAEP data and the readNAEP() function is telling me that it is "Unable to find matching .fr2 file" It seems to be looking for a sub-folder within the data directory called "path_to_data/select/parms" but this does not exist. 

Currently I am using the restricted data on the ADRF, the secure environment set up by NCES to access restricted use data. Are .fr2 files something I have to create? I found references to them in the EdSurvey documentation but no mention of what they should look like or how to create them. Currently I have access to codebooks stored in .txt or .pdf files, but these do not seem (easily) machine readable.

**Comment by tomfink** [comment]
Thanks for the inquiry @TKelleyKemple.  The `.fr2` files are provided alongside the NCES fixed-width data (`.dat`) files.  The `.fr2` file contains needed information to be able to correctly parse the data files, so is required.  It is not a user generated file.

The `.fr2` file should have the same filename as the `.dat` file, except with different file extensions.  So for example, the `M36NT2PM.dat` file would need the `M36NT2PM.fr2`  FR2 file.

The data, by default, is in the `data` folder (e.g., "x/data"), and the `.fr2` files are in the `select/parms` (e.g., "x/select/parms") folder. My best guess is that the default file structure was changed/altered, and you will need to manually set the `fr2Path` parameter for the `readNAEP` function to work.

To try to locate the location of the `.fr2` files, you could try to scan a folder/sub-folders using something like this:
`list.files("check_path", pattern = "[.]fr2$", full.names = TRUE, recursive = TRUE, ignore.case = TRUE)`

If you're unable to locate the associated `.fr2` file, then those will need to be obtained.

Once you have the location of the associated `.fr2` file you can then specify that file like so in `readNAEP`:
```
datPath <- "./extdata/data/M36NT2PM.dat"
fr2Path <- "./differentPath/M36NT2PM.fr2"

x <- readNAEP(path = datPath, frPath = fr2Path)
```

Let us know how it goes.  Feel free to close the issue if this helped resolve it.
Thank You!
-Tom

**Comment by TKelleyKemple** [comment]
Ok thank you for the clarification! Looks like I need to go back to the data folks to get the .fr2 files uploaded.
