### ISSUE TITLE
difference of performance between 3 or more groups

### ISSUE THREAD

**Issue by HGS80** [American-Institutes-for-Research/EdSurvey#28]
**We would asked you if we want to test the difference of performance between 3 or more groups, if the difference is significant or not, how can we do this in EdSurvey?
for example we want to test if there is a significant difference in the performance between the students who absent from school once a week, the students who absents once every two weeks, and the students who absent once a month.**

**Comment by pdbailey0** [comment]
@HGS80, for this you need a Wald test. We have [a vignette describing how to use the Wald test in EdSurvey](https://www.air.org/sites/default/files/EdSurvey-WaldTest.pdf).


Here is an example testing if levels of composite vary with "books in the home" (b013801) using the NAEP Primer. 
```
library(EdSurvey)
sdf <- readNAEP(system.file("extdata/data", "M36NT2PM.dat", package = "NAEPprimer"))
lma <- lm.sdf(composite ~ b013801, data=sdf)
waldTest(lma, "b013801")
# Wald test:
# ----------
# H0:
# b01380111-25 = 0
# b01380126-100 = 0
# b013801>100 = 0
# 
# Chi-square test:
# X2 = 1213.9, df = 3, P(> X2) = 0.0
# 
# F test:
# W = 391.6, df1 = 3, df2 = 60, P(> W) = 0
```
You can read the Wald test documentation (linked above) to see if you would prefer to use the chi-squared test or the F-test, but the results are very similar for this case, the p-value is nearly zero (actually printed as 0 above). The model also has an intercept (you can see this by printing the summary of `lma`), so under the null hypothesis, there is a single mean.

I hope this helps.
