### ISSUE TITLE
Weighting multilevel models with HSLS? 

### ISSUE THREAD

**Issue by cpdaniels** [American-Institutes-for-Research/EdSurvey#30]
Is it possible to do this given the way the weights have been constructed? I can't figure out if the stratification messes up the correspondence between level 1 weights (W1STUDENT) and level 2 weights (school weights). Normally I would just use the weights to construct level 1 = student | sch, but I'm not sure I can do this with HSLS. Any help would be greatly appreciated!! 

[edited by PB to remove unused HTML]

**Comment by pdbailey0** [comment]
@cpdaniels it seems like your question may just be the first paragraph and not all the code following it. Is that right? If not, can you please elaborate on any other details you wanted to provide?

**Comment by cpdaniels** [comment]
That’s correct, yes!

On Fri, Feb 25, 2022 at 11:38 AM Paul Bailey ***@***.***>
wrote:

> @cpdaniels
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cpdaniels&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=0m6FPoVAmOpezwWWd9LhTg&m=Zj_QSEyz6uf6hvbFFzL3b5wRibHPCpoz6LCA6f89kh3PWHbYHMDhWNWJIFmR8K7j&s=6JJE1CbGNjFQW9Mc_zePyE_z56twD-MzlUb94MaG5CA&e=>
> it seems like your question may just be the first paragraph and not all the
> code following it. Is that right? If not, can you please elaborate on any
> other details you wanted to provide?
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_American-2DInstitutes-2Dfor-2DResearch_EdSurvey_issues_30-23issuecomment-2D1051010204&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=0m6FPoVAmOpezwWWd9LhTg&m=Zj_QSEyz6uf6hvbFFzL3b5wRibHPCpoz6LCA6f89kh3PWHbYHMDhWNWJIFmR8K7j&s=3uPXd3qgDcpSdUO_LqMbgJZD7CObCCh8LZquIg_NZVc&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADLSTPQ4IVN7N565T3GDD3TU46V6RANCNFSM5PKUCUZQ&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=0m6FPoVAmOpezwWWd9LhTg&m=Zj_QSEyz6uf6hvbFFzL3b5wRibHPCpoz6LCA6f89kh3PWHbYHMDhWNWJIFmR8K7j&s=Q3Q10GfDKzwYyCf2PldPmZpM_WqLnhMVLjRtwoKOX9Q&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=0m6FPoVAmOpezwWWd9LhTg&m=Zj_QSEyz6uf6hvbFFzL3b5wRibHPCpoz6LCA6f89kh3PWHbYHMDhWNWJIFmR8K7j&s=8HPVcZYjY2FdHcgJ2hXvvpDhbB26OgG1TSwDo01TxGA&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=0m6FPoVAmOpezwWWd9LhTg&m=Zj_QSEyz6uf6hvbFFzL3b5wRibHPCpoz6LCA6f89kh3PWHbYHMDhWNWJIFmR8K7j&s=7mQC7CjcICV1m9Nzm9Gf-6pEnSRohyrn2yHzjBF7FYI&e=>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>
-- 
Chelsea Daniels
NYU Sociology
NYC Reducing Inequality Network Fellow
IES-Predoctoral Interdisciplinary Research Training Fellow

**Comment by pdbailey0** [comment]
@cpdaniels Thanks for the clarification. Now that I understand, I'm trying to find who would have an answer to your question.

**Comment by pdbailey0** [comment]
@cpdaniels this question is more about using HSLS weights than EdSurvey specifically, so I'm going to ask you to contact Elise.Christopher@ed.gov at NCES directly.

Once you know what you plan to do, I'm happy to help you actually do it with `EdSurvey` and/or `WeMix`.
