### ISSUE TITLE
"Building the weights" in long format

### ISSUE THREAD

**Issue by niguarino** [American-Institutes-for-Research/EdSurvey#34]
Can you describe what you're doing when you "built the weights" in post #3? I am not sure how to incorporate the weights in order to run a properly weighted student-level fixed effects model. Also, I am not sure why you subset the initial data set. Please address this if it influenced how you built the weights. Thank you!

**Comment by pdbailey0** [comment]
@niguarino those are for example purposes only, to get a model to run. I would not use those weights. I'll update the code to make that clearer.

What weights to use is an open question with ongoing debate in the literature. Here is [a recent paper](https://link.springer.com/article/10.1186/s40536-021-00099-0) on the topic.

If you have questions about weighting a particular dataset, please ask NCES.
