### ISSUE TITLE
Models that adjust for clustered standard errors

### ISSUE THREAD

**Issue by niguarino** [American-Institutes-for-Research/EdSurvey#35]
I would like to run an econometric student-level fixed effects model (ideally, a logistic FE model) using the HSLS data. `EdSurvey` doesn't yet have some important features that would make this easier/possible:

1. A way to suppress the output of the fixed effect so potentially hundreds of unimportant coefficients are not displayed
2. More importantly, a way to cluster the standard errors so I am properly estimating them

It would be great to have an option in the regression commands (like `logit.sdf()`) to account for the clustering of standard errors.

There isn't another option in `EdSurvey` that I'm aware of that would allow me to properly estimate standard errors given the clustered nature of the data when looking across more than one survey wave. I think the `survey` package in R wouldn't allow me to do this, either, based on my read of the `svyglm()` command. The best option to my knowledge is to extract my recoded data set using `getData()` and moving it from R to Stata to work with its svy commands. Please let me know if you're aware of anther option, though.

**Comment by pdbailey0** [comment]
@niguarino, EdSurvey with the jackknife variance estimator uses a cluster-robust standard error consistent with the sampling design!

As for a fixed effects estimator, no, that is not included. I'll mark that as an RFE. Do you have one you recommend?

Meanwhile, I'd probably grab the coefficients matrix from the object returned by `lm.sdf` and use regex to filter it. Let me know if you need help with that.

**Comment by niguarino** [comment]
@pdbailey0, thanks for your response. Does this mean I can run the following to estimate cluster-robust standard errors? How does `logit.sdf()` (in the last command I run below) know that I am clustering on student ID?

```
# Load libraries
library(EdSurvey)
library(tidyverse)

# Load data
hsls_stud <- readHSLS(
  path = "YOURPATHHERE", # Add your path here
  filename = "hsls_16_student_v1_0.sav"
)

# Get data
analytic_stufe <- getData(
  data = hsls_stud,
  varnames = c(
    "stu_id", 
    "x1stuedexpct", "x2stuedexpct", 
    "x1txmtscor", "x2txmtscor",
    "w2w1stu"
  ),
  omittedLevels = TRUE,
  recode = list(
    x1stuedexpct = list(
      from = c("LESS THAN HIGH SCHOOL", "HIGH SCHOOL DIPLOMA OR GED", "START AN ASSOCIATE'S DEGREE", "COMPLETE AN ASSOCIATE'S DEGREE", "START A BACHELOR'S DEGREE"),
      to = c("Lower than BA")
    ),
    x1stuedexpct = list(
      from = c("COMPLETE A BACHELOR'S DEGREE", "START A MASTER'S DEGREE", "COMPLETE A MASTER'S DEGREE", "START PH.D/M.D/LAW/OTHER PROF DEGREE", "COMPLETE PH.D/M.D/LAW/OTHER PROF DEGREE"),
      to = c("BA or higher")
    ),
    x2stuedexpct = list(
      from = c("LESS THAN HIGH SCHOOL COMPLETION", "COMPLETE HS DIPLOMA/GED/ALTERNATIVE HS CREDENTIAL", "START, BUT NOT COMPLETE CERTIFICATE/DIPLOMA FROM SCHOOL PROVIDING OCC TRAINING", "COMPLETE CERTIFICATE/DIPLOMA FROM SCHOOL PROVIDING OCCUPATIONAL TRAINING", "START, BUT NOT COMPLETE ASSOCIATE'S DEGREE", "COMPLETE ASSOCIATE'S DEGREE", "START, BUT NOT COMPLETE BACHELOR'S DEGREE"),
      to = c("Lower than BA")
    ),
    x2stuedexpct = list(
      from = c("COMPLETE BACHELOR'S DEGREE", "START, BUT NOT COMPLETE MASTER'S DEGREE", "COMPLETE MASTER'S DEGREE", "START, BUT NOT COMPLETE PH.D./M.D./LAW DEGREE/HIGH LEVEL PROFESSIONAL DEGREE", "COMPLETE PH.D./M.D./LAW DEGREE/OTHER HIGH LEVEL PROFESSIONAL DEGREE"),
      to = c("BA or higher")
    )
  )
)

# Isolate 9th grade student expectation data
analytic_stufe_expf09 <- analytic_stufe %>%
  select(stu_id, x1stuedexpct) %>%
  mutate(year = "9th grade", expect_f = as.factor(x1stuedexpct)) %>%
  select(stu_id, year, expect_f)

# Isolate 11th grade student expectation data
analytic_stufe_expf11 <- analytic_stufe %>%
  select(stu_id, x2stuedexpct) %>%
  mutate(year = "11th grade", expect_f = as.factor(x2stuedexpct)) %>%
  select(stu_id, year, expect_f)

# Isolate 9th grade student math score data
analytic_stufe_math09 <- analytic_stufe %>%
  select(stu_id, x1txmtscor) %>%
  mutate(year = "9th grade", mathscore = x1txmtscor) %>%
  select(stu_id, year, mathscore)

# Isolate 11th grade student math score data
analytic_stufe_math11 <- analytic_stufe %>%
  select(stu_id, x2txmtscor) %>%
  mutate(year = "11th grade", mathscore = x2txmtscor) %>%
  select(stu_id, year, mathscore)

# Isolate w2w1stu weights with student ID
analytic_stufe_weights <- analytic_stufe %>% 
  select(stu_id, starts_with("w2w1stu"))

# Merge 9th grade data by student ID and year
analytic_stufe_9th <- analytic_stufe_expf09 %>%
  left_join(
    analytic_stufe_math09,
    by = c("stu_id", "year")
  )

# Merge 11th grade data by student ID and year
analytic_stufe_11th <- analytic_stufe_expf11 %>%
  left_join(
    analytic_stufe_math11,
    by = c("stu_id", "year")
  )

# Combine 9th and 11th grade data by binding rows (same column structure in both objects) to create long data set
analytic_stufe_9th11thall <- analytic_stufe_9th %>%
  bind_rows(analytic_stufe_11th) %>% 
  mutate(stu_id_f = as.factor(stu_id), year = factor(year, levels = c("9th grade", "11th grade"))) %>% 
  # Add weights to data set
  left_join(
    analytic_stufe_weights,
    by = c("stu_id")
  )

# Rebind attributes
analytic_stufe_9th11thall_adj <- rebindAttributes(analytic_stufe_9th11thall, hsls_stud)

# Run student-level fixed effects logistic regression to estimate the within-student effect of change in math score on change in student expectations
logit.sdf(
  formula = expect_f ~ mathscore + stu_id_f,
  data = analytic_stufe_9th11thall_adj,
  weightVar = "w2w1stu"
)
```

When I run this, I get the following error:

```
Error: cannot allocate vector of size 2.8 Gb
```

Will running this depend on enhancement? I think the other option is to manually de-mean the variables of interest to avoid adding the student IDs in the regression. I can't do this, however, in a logistic regression.

**Comment by pdbailey0** [comment]
The variance estimator accounts for covariance in the sample as drawn--so the PSU-level. I'd encourage you to look in Wolters "Introduction to Variance Estimation" in chapter 4, or the materials for variance estimation for HSLS.

The error message is because your computer is out of memory. There are lots of possible causes of that.

**Comment by niguarino** [comment]
The PSU-level in the HSLS is the school-level, as schools were first sampled before sampling students in schools. In my student-level fixed effects model, though, I also want to account for clustering that is taking place at the student-level, where observations (two of them, in my case) are clustered within students. My fixed effects model is taking the form described [here](https://www.econometrics-with-r.org/10-3-fixed-effects-regression.html), where my goal is to estimate beta_1 (effect of a change in math score on a change in expectations for college).

I think what you're saying is that the variance estimation in `EdSurvey` is taking care of the clustered nature of the sampling structure at the PSU-level (students nested in schools). It seems, though, that there isn't currently a way to also account for the clustered nature of my model in `EdSurvey`. Is this right? I apologize for any misunderstandings on my end.

**Comment by pdbailey0** [comment]
It looks to me like you found a bug in `glm2` instead of running your logit.sdf call try this:
```
g2 <- glm2(
  formula = expect_f ~ mathscore + stu_id_f,
  data = analytic_stufe_9th11thall_adj,
  family=binomial()
)
```

I also took out the tidyverse import to see if that was the issue and it does not seem to be. Can you see if this call works for you?

**Comment by niguarino** [comment]
I get the same error message when I run the`glm2()` code you provided:

```
Error: cannot allocate vector of size 2.8 Gb
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
```

**Comment by pdbailey0** [comment]
may I request you report the bug to `glm2`? The only contact info I can see is the email address of the maintainer on CRAN. Looking at the NEWS, it seems the maintainer is open to suggested fixes.

**Comment by niguarino** [comment]
Yes, I can do this. May I check my understanding before reaching out?

1. `glm2()` underlies `logit.sdf()`. There seems to be a bug in `glm2()`, which is causing a problem when I try to run either `logit.sdf()` or `glm2()`. [How do we know this is not an actual issue with my computer memory?]
2. Regardless, it seems that `logit.sdf()` can't address my issue of adjusting standard errors for observations nested within students when using panel data. I'm guessing that I would need to signify in my code that I am clustering at the student level. Is that correct?

**Comment by pdbailey0** [comment]
@niguarino great questions!

1. Correct. We know is not you because I have the same issue.
2. the clustering is consistent with the survey design. I advise against using clustering that is not consistent with the survey design.

**Comment by niguarino** [comment]
OK, thank you. I sent the bug report.

**Comment by pdbailey0** [comment]
@niguarino I edited your code so that it would run on a new machine by adding `downloadHSLS` and using the home directory (which is universal across operating systems). I would add that the glm2 issue can be seen by replacing the `logit.sdf` call with
```
g2 <- glm2(
  formula = expect_f ~ mathscore + stu_id_f,
  data = analytic_stufe_9th11thall_adj,
  family=binomial()
)
```

**Comment by pdbailey0** [comment]
One solution might be to allow a user supplied glm function. Here `feglm` from the `fixef` package may work

```
require(fixef)
g2 <- feglm(
  I(expect_f == "BA or higher") ~ mathscore | stu_id_f,
  data = analytic_stufe_9th11thall,
  family=binomial()
)
```

**Comment by niguarino** [comment]
Do you mean did I try selecting only the observations for an ID where there was a change in the outcome and plugging that data into `glm2()`? I haven't, but I can try that.

**Comment by pdbailey0** [comment]
Yes

**Comment by niguarino** [comment]
That worked very quickly. I am now trying to arrange it so that I can try this with `logit.sdf()`.

**Comment by niguarino** [comment]
Here's what I ran:

```
# Load libraries
library(EdSurvey)
library(tidyverse)

downloadHSLS("~/")

# Load data
hsls_stud <- readHSLS(
  path = "~/HSLS/2009/", # Add your path here
  filename = "hsls_16_student_v1_0.sav"
)

# Get data
analytic_stufe <- getData(
  data = hsls_stud,
  varnames = c(
    "stu_id", 
    "x1stuedexpct", "x2stuedexpct", 
    "x1txmtscor", "x2txmtscor",
    "w2w1stu"
  ),
  omittedLevels = TRUE,
  recode = list(
    x1stuedexpct = list(
      from = c("LESS THAN HIGH SCHOOL", "HIGH SCHOOL DIPLOMA OR GED", "START AN ASSOCIATE'S DEGREE", "COMPLETE AN ASSOCIATE'S DEGREE", "START A BACHELOR'S DEGREE"),
      to = c("Lower than BA")
    ),
    x1stuedexpct = list(
      from = c("COMPLETE A BACHELOR'S DEGREE", "START A MASTER'S DEGREE", "COMPLETE A MASTER'S DEGREE", "START PH.D/M.D/LAW/OTHER PROF DEGREE", "COMPLETE PH.D/M.D/LAW/OTHER PROF DEGREE"),
      to = c("BA or higher")
    ),
    x2stuedexpct = list(
      from = c("LESS THAN HIGH SCHOOL COMPLETION", "COMPLETE HS DIPLOMA/GED/ALTERNATIVE HS CREDENTIAL", "START, BUT NOT COMPLETE CERTIFICATE/DIPLOMA FROM SCHOOL PROVIDING OCC TRAINING", "COMPLETE CERTIFICATE/DIPLOMA FROM SCHOOL PROVIDING OCCUPATIONAL TRAINING", "START, BUT NOT COMPLETE ASSOCIATE'S DEGREE", "COMPLETE ASSOCIATE'S DEGREE", "START, BUT NOT COMPLETE BACHELOR'S DEGREE"),
      to = c("Lower than BA")
    ),
    x2stuedexpct = list(
      from = c("COMPLETE BACHELOR'S DEGREE", "START, BUT NOT COMPLETE MASTER'S DEGREE", "COMPLETE MASTER'S DEGREE", "START, BUT NOT COMPLETE PH.D./M.D./LAW DEGREE/HIGH LEVEL PROFESSIONAL DEGREE", "COMPLETE PH.D./M.D./LAW DEGREE/OTHER HIGH LEVEL PROFESSIONAL DEGREE"),
      to = c("BA or higher")
    )
  )
)

# Isolate 9th grade student expectation data
analytic_stufe_expf09 <- analytic_stufe %>%
  select(stu_id, x1stuedexpct) %>%
  mutate(year = "9th grade", expect_f = as.factor(x1stuedexpct)) %>%
  select(stu_id, year, expect_f)

# Isolate 11th grade student expectation data
analytic_stufe_expf11 <- analytic_stufe %>%
  select(stu_id, x2stuedexpct) %>%
  mutate(year = "11th grade", expect_f = as.factor(x2stuedexpct)) %>%
  select(stu_id, year, expect_f)

# Isolate 9th grade student math score data
analytic_stufe_math09 <- analytic_stufe %>%
  select(stu_id, x1txmtscor) %>%
  mutate(year = "9th grade", mathscore = x1txmtscor) %>%
  select(stu_id, year, mathscore)

# Isolate 11th grade student math score data
analytic_stufe_math11 <- analytic_stufe %>%
  select(stu_id, x2txmtscor) %>%
  mutate(year = "11th grade", mathscore = x2txmtscor) %>%
  select(stu_id, year, mathscore)

# Isolate w2w1stu weights with student ID
analytic_stufe_weights <- analytic_stufe %>% 
  select(stu_id, starts_with("w2w1stu"))

# Merge 9th grade data by student ID and year
analytic_stufe_9th <- analytic_stufe_expf09 %>%
  left_join(
    analytic_stufe_math09,
    by = c("stu_id", "year")
  )

# Merge 11th grade data by student ID and year
analytic_stufe_11th <- analytic_stufe_expf11 %>%
  left_join(
    analytic_stufe_math11,
    by = c("stu_id", "year")
  )

# Combine 9th and 11th grade data by binding rows (same column structure in both objects) to create long data set
analytic_stufe_9th11thall <- analytic_stufe_9th %>%
  bind_rows(analytic_stufe_11th) %>% 
  mutate(stu_id_f = as.factor(stu_id), year = factor(year, levels = c("9th grade", "11th grade"))) %>% 
  # Add weights to data set
  left_join(
    analytic_stufe_weights,
    by = c("stu_id")
  )

# Identify IDs where expectations change versus not change between 9th and 11th grades
analytic_stufe_9th11thall2 <- analytic_stufe_9th11thall %>% 
  group_by(stu_id_f, expect_f) %>% 
  count() %>% 
  group_by(stu_id_f) %>% 
  count() %>% 
  mutate(change = factor(if_else(n == 1, "No change", "Change"), levels = c("No change", "Change"))) %>% 
  select(stu_id_f, change) %>% 
  right_join(
    analytic_stufe_9th11thall,
    by = "stu_id_f"
  ) %>% 
  select(stu_id_f, year, expect_f, change, everything()) 
  # filter(change == "Change")

# Create a data set where only changers exist for future use with glm2()
analytic_stufe_9th11thall3 <- analytic_stufe_9th11thall2 %>% 
  filter(change == "Change")

# Rebind attributes
analytic_stufe_9th11thall_adj <- rebindAttributes(analytic_stufe_9th11thall2, hsls_stud)

# Subset changers for use with logit.sdf()
analytic_stufe_9th11thall_adj_sub <- subset(analytic_stufe_9th11thall_adj, subset = change == "Change")

# Run model where observations are clustered at the student-level (classic econometric student-level FE model)
g2 <- feglm(
  I(expect_f == "BA or higher") ~ mathscore | stu_id_f,
  data = analytic_stufe_9th11thall2,
  family = binomial()
)

summary(g2)

# Run glm2() with only changers to see if this works
g22 <- glm2(
  formula = expect_f ~ mathscore + stu_id_f,
  data = analytic_stufe_9th11thall3,
  family = binomial()
)

summary(g22)
# Standard errors are much bigger here than in FE model, which makes sense because SEs are not being adjusted here

# Run logit.sdf() with changers only; adjusts for sampling design (stratification and clustering) by clustering at PSU (i.e., school) level
g222 <- logit.sdf(
  expect_f ~ mathscore + stu_id_f,
  analytic_stufe_9th11thall_adj_sub,
  weightVar = "w2w1stu"
)

summary(g222)
```

`logit.sdf()` is still running after about 2.5 hours. I will update you once it is finished running.

**Comment by niguarino** [comment]
`logit.sdf()` has been running for more than five hours. I will allow it to run overnight and will post what happened tomorrow morning.

**Comment by pdbailey0** [comment]
@niguarino did you intend to use this data?
```
# Rebind attributes
analytic_stufe_9th11thall_adj <- rebindAttributes(analytic_stufe_9th11thall3, hsls_stud)
```

**Comment by niguarino** [comment]
@pdbailey0 do you have any recommendations on what to do given that using `logit.sdf()` with the subset has too long of a run time?

**Comment by pdbailey0** [comment]
I do not. I'm going to close this issue because I think it has morphed into the request in issue https://github.com/American-Institutes-for-Research/EdSurvey/issues/41
