### ISSUE TITLE
How to get a subset of only students who reached the advanced level from NAEP 2019 dataset

### ISSUE THREAD

**Issue by yaoyang1707** [American-Institutes-for-Research/EdSurvey#36]
Thanks for using EdSurvey! Please follow the instructions below when requesting a new feature in EdSurvey.
---

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

How can I create a subset with only students who reached the advanced level of 2019 math NAEP in Edsurvey?

**Describe alternatives you've considered**

**Additional context**
Add any other context, codes, outputs, or screenshots about the feature request here.

For example, I want to compare the mean score difference of female and male students who reached the 2019 math NAEP advanced level. And I also want to run a Multilevel level modeling with students and schools variables, but I am only interested in the advanced achievement (outcome variables). So I want to have a subset of the students who reached the advanced level.

**Comment by tzhangumd** [comment]
@yaoyang1707 I would recommend you to read our new EdSurvey ebook, focusing on the data manipulation chapter: https://naep-research.airprojects.org/Portals/0/EdSurvey_A_Users_Guide/_book/dataManipulation.html. 

Let us know if it addresses your questions. :)

**Comment by pdbailey0** [comment]
It seems there is no question here so I'm closing this issue. Please feel free to open a new issue with a question.
