### ISSUE TITLE
N (sample size) in descriptive analysis

### ISSUE THREAD

**Issue by yaoyang1707** [American-Institutes-for-Research/EdSurvey#37]
Thanks for using EdSurvey! Please follow the instructions below when requesting a new feature in EdSurvey.
---

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

When I use the commands to compute the N, weightedN, Weighted percentage, standard error of 2019 Math NAEP:
aLev0<achievementLevels(achieveemntVars=c("composite", "dsex"), aggregateBy="dsex", data=sdf, returnCumulative=TRUE)
aLev0$discrete

The output shows that N for males who reached the advanced level is 7052.05, for females is 4424.05. 
I am wondering why there are some decimals. I assume the N should be an integer.

**Describe alternatives you've considered**

**Additional context**
Add any other context, codes, outputs, or screenshots about the feature request here.

**Comment by pdbailey0** [comment]
It seems there is no question here so I'm closing this issue. Please feel free to open a new issue with a question.

**Comment by tzhangumd** [comment]
@yaoyang1707 Could you edit your questions? See an example here https://github.com/American-Institutes-for-Research/EdSurvey/issues/33.
