### ISSUE TITLE
What does dofAB mean in gap analysis

### ISSUE THREAD

**Issue by yaoyang1707** [American-Institutes-for-Research/EdSurvey#38]
Thanks for using EdSurvey! Please follow the instructions below when requesting a new feature in EdSurvey.
---

**Is your feature request related to a problem? Please describe.**

I am trying to compute the gap analysis between female and males' math achievement.

In the edsurvey output, what does "dofAB" mean, does it mean degrees of freedom. In the output I have, it shows dofAB= 46.9006. May I know what it means?

Thank you

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, codes, outputs, or screenshots about the feature request here.

**Comment by pdbailey0** [comment]
It seems there is no question here so I'm closing this issue. Please feel free to open a new issue with a question.

**Comment by tzhangumd** [comment]
Use `?gap` command to pull out the gap function description. @yaoyang1707 You should find your answer there.

**Comment by tzhangumd** [comment]
@yaoyang1707 Next time to avoid confusion, could you state your questions just following the direction from this GitHub? (see examples in other issues)

**Comment by yaoyang1707** [comment]
Thank you  so much for your answer. Sorry for the confusion. I will follow the example to propose the question next time.
