### ISSUE TITLE
Support for .am files, NALS/NAAL surveys

### ISSUE THREAD

**Issue by Deleetdk** [American-Institutes-for-Research/EdSurvey#39]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
EdSurvey can currently read many survey files. However, the 1992 NALS, and the 2003 NAAL are not among them. These survey files are currently available in the obscure .am file format. This format requires the AM Statistical Software. This software only works on Windows. But even on Windows, it seems the software add-on for exporting the data to normal formats is missing. [See this question on Cross-Validated.](https://stats.stackexchange.com/questions/569042/exporting-data-from-am-format-am-statistical-software) Thus, a good solution here would be to add support for these surveys in this R package, so that people can use the NALS/NAAL surveys.

**Describe alternatives you've considered**
I have tried to get the AM Statistical Software to work, per the link above. I also emailed Paul Bailey if he could send me the converted files. He suggested I add a feature request here. Next up will be to email the surviving authors of the [Technical Report and Data File User’s Manual For the 1992 National Adult Literacy Survey](https://nces.ed.gov/pubsearch/pubsinfo.asp?pubid=2001457) report, whose chapter 15 stated there are SPSS files for this dataset at the NCES website, but I cannot find them.

**Comment by pdbailey0** [comment]
NCES has decided this is not a funding priority for EdSurvey but would happily entertain submitted code consistent with our [code contribution policy](https://github.com/American-Institutes-for-Research/EdSurvey#contributions).
