### ISSUE TITLE
Error in Mixed-effects Models documentation?

### ISSUE THREAD

**Issue by niguarino** [American-Institutes-for-Research/EdSurvey#4]
The [documentation on mixed-effects models](https://www.air.org/sites/default/files/EdSurvey-Mixed_Models.pdf) has a confusing sentence on page 2: 

> As discussed in Rabe-Hesketh & Skrondal (2006), using unscaled weights in mixed models can lead to biased estimates, especially when level-1 weights are very different from 1 and cluster size (e.g., the number of students within a school) is small.

Can you explain what you mean by "especially when level-1 weights are very different from 1?" I'm not sure what the second "1" means here.

**Comment by pdbailey0** [comment]
@niguarino sorry that was unclear. I think we are saying that a weight of 100 would be very different from a weight of 1.

However, we're not here to help you weight your data, and when we last looked this appeared to be an open question in the literature, so we're not taking a stance on it, except to note that some surveys have a recommended weighting scheme, and we implement those when we could find them.

I would suggest you read Rabe-Hesketh & Skrondal (full citation in the document you linked) or whatever literature you think is relevant, and decide on weights for yourself.

Please do upgrade to at least EdSurvey 2.6.9 which has clearer output about what weights were used.

**Comment by niguarino** [comment]
@pdbailey0 I understand what you're trying to say now. Thank you!
