### ISSUE TITLE
RFI: Fixed effects estimator

### ISSUE THREAD

**Issue by niguarino** [American-Institutes-for-Research/EdSurvey#41]
I'd like to request a fixed effects estimator option in `lm.sdf()`. I'm trying to run a student-level econometric fixed effects model using the HSLS data while applying the panel weights to produce the properly adjusted standard errors. I can accomplish this using `lm.sdf()` with student ID as a factor in the regression model because I have a relatively small sample size (about 2800 students over two time points), but it takes a long time to run, and if I increase the sample to about twice this amount, the command will only produce an error, saying the vector size being too large (after running for about three hours).

Fixed effects models don't seem to be too uncommon for NCES data. Here are a couple of studies that use NCES data with fixed effects:

- [This study](https://direct-mit-edu.turing.library.northwestern.edu/edfp/article/14/4/523/12335/The-Returns-to-Education-at-Community-Colleges-New) uses NELS and ELS and applies school-level fixed effects in an econometric study of the effect of community college on earnings
- [This study](https://onlinelibrary-wiley-com.turing.library.northwestern.edu/doi/abs/10.1002/pam.20174) uses econometric methods with the ECLS:K, including using county-level fixed effects
- A book chapter uses the NELS with student-level fixed effects (see Jacob & Wilder Linkow, 2011, p. 157, in _Whither Opportunity? Rising inequality, schools, and children's life chances_ by G. Duncan & R. Murnane (Eds.)). (I think they didn't apply the panel weights.)

The functionality could be similar to the `fixest` package, where the user designates any fixed effects by inserting them in a regression equation after the `|` sign. For example, ```expect_n ~ afford | stu_id_f```. The output could look similar to Stata, where the fixed effects estimates are separated from the other regression coefficients, appearing below the output for the variables of interest. The output could cut off after 100 fixed effects estimators if there are more as these aren't really important for the user.

I think the other option would be to use WeMix by group-mean centering student variables at level 1 and adding a fixed effect at level 2. Raudenbush and Bryk (2002) in their HLM textbook say this is equivalent to the econometric fixed effects model and can isolate the within group estimator (p. 135-137). I think in this case I would want to use no weights at level 1 and the BRR weights at level 2, but I don't think this is possible with the way mixed.sdf() is set up. I could be wrong about the weighting scheme, though.

I think the alternative would be to move the data into another program like Stata if I want to run a fixed effects model with a larger student sample.

Thanks for your consideration.

**Comment by pdbailey0** [comment]
NCES has decided this is not a funding priority for EdSurvey but would happily entertain submitted code consistent with our [code contribution policy](https://github.com/American-Institutes-for-Research/EdSurvey#contributions).

**Comment by niguarino** [comment]
OK, thank you for asking.
