### ISSUE TITLE
Request: Wald test for summed coefficients

### ISSUE THREAD

**Issue by niguarino** [American-Institutes-for-Research/EdSurvey#44]
I know there is a Wald test feature in EdSurvey to test whether certain variables can be removed from a model. I'm wondering if the Wald test command can be expanded to include a test of summed coefficients. For example, with HSLS, I would like to test for whether the effect of affordability beliefs for girls is equal to 0 or not. This requires summing the main effect on affordability beliefs with the interaction effect of affordability beliefs on sex and running a hypothesis test (null hypothesis: summation of coefficients = 0). It seems that this is possible in Stata using the "test" command but not in EdSurvey. Is it possible to add this feature? Thanks for your help.

**Comment by pdbailey0** [comment]
NCES has decided not to implement this.
