### ISSUE TITLE
Recode/Regroup achievement levels for Regression Analysis

### ISSUE THREAD

**Issue by lostandfound8** [American-Institutes-for-Research/EdSurvey#46]
**1) Context**

I am a student from Germany currently working on my master thesis in educational science and therefore working with PIAAC datasets from various countries using EdSurvey in R-Studio. (Also I am a beginner in R and on GitHub and hope this is a correct place of contact for my inquiry.)

**2) Aims**

**A)** I would like to do a multivariate regression (mvrlm.sdf) using the six achievement levels (i.e. of Literacy, but basically for each competence individually) as my dependent variable, but recoding/grouping them to only three achievement levels (i.e. levels 0 and 1 as "-" or 1, levels 2 and 3 as average or 2 and levels 4 and 5 as "+" or 3).
(--> competencies: Lit (Literacy), Num (Numeracy), PSL / ICT (Problem Solving in Technology-rich environments using Information and Communication Technology))

**B)** Secondly I would like to do a Linear Regression (unsure whether glm.sdf or lm.sdf?) within only the average achievement level to examine the Variance of the Predictors within this level.

**3) Problem and considered alternatives**

**A)** Since the Competencies are no singular Variable but include the ten Plausible Values (PVs) and weights, I am unsure of how best to recode them without unintentionally not taking this into account (i.e. with the recode-function of EdSurvey or Car-package). What I have read so far indicates that the recode-function of EdSurvey is only meant for discrete variables and recoding label-names, yet not the labels themselves, Cut-off-points or the like).

**B)** Depending on whether the achievement levels can be recoded, this determines the formula for the Linear Regression and how to "extract" specific achievement levels. Trying doing so via subset-function did not work due to competencies not being singular variables (i.e. "sdf_allM_Lit <- subset(sdf_all, (lit > 226 & lit < 325))")

**4) desired solutions**

**A)** At best would be a code for recoding achievement levels considering the PVs and weights, that I can then use as dependent variables for the multivariate regression
**B)** and later on as a subset (?) for a linear regression.

**5) Additional Info**
If required I can upload my current R-Script or answer further questions regarding the thesis.

**Comment by pdbailey0** [comment]
I’m not entirely sure I understand the question, or maybe questions l, but have you looked at achievementLevels function, which lets you set the cut points with an argument similar to that.

I hope you do not need to recode variables with that.

Linear regression in R is done without lm, in EdSurvey wirh lm.sdf. I hope this helps.

Best,
Paul
________________________________
From: lostandfound8 ***@***.***>
Sent: Wednesday, July 13, 2022 12:07:50 PM
To: American-Institutes-for-Research/EdSurvey ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [American-Institutes-for-Research/EdSurvey] Recode/Regroup achievement levels for Regression Analysis (Issue #46)

External email alert: Be wary of links & attachments.


** 1) Context **

I am a student from Germany currently working on my master thesis in educational science and therefore working with PIAAC datasets from various countries using EdSurvey in R-Studio. (Also I am a beginner in R and on GitHub and hope this is a correct place of contact for my inquiry.)

** 2) Aims **

A) I would like to do a multivariate regression (mvrlm.sdf) using the six achievement levels (i.e. of Literacy, but basically for each competence individually) as my dependent variable, but recoding/grouping them to only three achievement levels (i.e. levels 0 and 1 as "-" or 1, levels 2 and 3 as average or 2 and levels 4 and 5 as "+" or 3).
(--> competencies: Lit (Literacy), Num (Numeracy), PSL / ICT (Problem Solving in Technology-rich environments using Information and Communication Technology))

B) Secondly I would like to do a Linear Regression (unsure whether glm.sdf or lm.sdf?) within only the average achievement level to examine the Variance of the Predictors within this level.

** 3) Problem and considered alternatives **

A) Since the Competencies are no singular Variable but include the ten Plausible Values (PVs) and weights, I am unsure of how best to recode them without unintentionally not taking this into account (i.e. with the recode-function of EdSurvey or Car-package). What I have read so far indicates that the recode-function of EdSurvey is only meant for discrete variables and recoding label-names, yet not the labels themselves, Cut-off-points or the like).

B) Depending on whether the achievement levels can be recoded, this determines the formula for the Linear Regression and how to "extract" specific achievement levels. Trying doing so via subset-function did not work due to competencies not being singular variables (i.e. "sdf_allM_Lit <- subset(sdf_all, (lit > 226 & lit < 325))")

** 4) desired solutions **

A) At best would be a code for recoding achievement levels considering the PVs and weights, that I can then use as dependent variables for the multivariate regression
B) and later on as a subset (?) for a linear regression.

** 5) Additional Info **
If required I can upload my current R-Script or answer further questions regarding the thesis.

**Comment by lostandfound8** [comment]
Hello Paul, thank you for your fast reply! 

So my main question is how I can "save" the customized CutPoints of the achievement levels in order to use these as separate dependent variables within a multivariate regression Analysis. I was able to change the CutPoints using the achievementLevels-function (to 0, 226, 326) but when checking them using the showCutPoints-function for the data, the Output showed the datas default CutPoints (176, 226, 276, 326, 376). 
I also don't seem to be able to fit achievement levels as dependent variables into the formula without receiving warning messages or generating an output with only intercept 0. 

Here is my code so far (I had tried various things, but unfortunatly I didn't save every code I tried):

`# Philipps-University Marburg - Institute for Educational Science

# MASTER-THESIS

# Title (translated from German): „What maketh the middle?“ – International Comparison of Predictors of average competence based on PIAAC 

# Research Questions and suitable Analysis (not yet specified exactly):

# A) What are the predictors of average adult proficiency levels?
# / How can it be that "mixed" people (e.g. academics and non-academics) end up in this area of competence?
# Multivariate regression (achievement levels 0&1, 2&3 and 4&5 as dependent variables)

# B) To what extent do the predictors differ within the average competence level (e.g. with regard to one's own formal level of education and that of the parents?)?
# = Linear regression, calculate variance


# Data: PIAAC PublicUseFiles (available via https://webfs.oecd.org/piaac/puf-data/CSV/)

# R-Script using EdSurvey ("Large-Scale Cognitive Assessment: Analyzing PIAAC-Data" by Maehler & Rammstedt 2020)



#--------------------------- Preparation ------------------------------


help(package="EdSurvey")


# load packages
library(carData)
library(car)
library(lfactors)
library(EdSurvey)


# manual data download instead of using: downloadPIAAC(root="~/", cycle = 1, cache = FALSE, verbose = TRUE)


# loading data as EdSurvey-Frame
deu <- readPIAAC('~/PIAAC/Cycle 1/', countries='DEU')
fin <- readPIAAC('~/PIAAC/Cycle 1/', countries='FIN')
pol <- readPIAAC('~/PIAAC/Cycle 1/', countries='POL')
usa <- readPIAAC('~/PIAAC/Cycle 1/', countries='usa12_14')

# checking data

# Germany
showPlausibleValues(deu, verbose=TRUE)
showWeights(deu)
getAttributes(deu,'omittedLevels')
deu # achievement levels
View(showCodebook(deu))

dim(deu) # N=5465; Variables=1328
colnames(deu) # Variable-labels
summary(deu) # List of 23

# Finland
showPlausibleValues(fin, verbose=TRUE)
showWeights(fin)
getAttributes(fin,'omittedLevels')
fin # achievement levels

dim(fin) # N=5464; Variables=1328
colnames(fin) # Variable-labels
summary(fin) # List of 23

# Poland
showPlausibleValues(pol, verbose=TRUE)
showWeights(pol)
getAttributes(pol,'omittedLevels')
pol # achievement levels

dim(pol) # N=9366; Variables=1328
colnames(pol) # Variable-labels
summary(pol) # List of 23

# USA 2012/2014
showPlausibleValues(usa, verbose=TRUE)
showWeights(usa)
getAttributes(usa,'omittedLevels')
usa # achievement levels

dim(usa) # N=7921; Variables=1328
colnames(usa) # Variablen-lables
summary(usa) # List of 23


# Exploring data (using Germany as an example)

# Germany
# achievement levels 
showCutPoints(data = deu) # CutPoints see below

# Literacy:  176, 226, 276, 326, 376
aLev_lit <- achievementLevels(achievementVars = c("lit"),
                              data = deu, returnCumulative = TRUE)
aLev_lit

# Numeracy:  176, 226, 276, 326, 376
aLev_num <- achievementLevels(achievementVars = c("num"),
                              data = deu, returnCumulative = TRUE)
aLev_num

# Problem Solving:  241, 291, 341
aLev_psl <- achievementLevels(achievementVars = c("psl"),
                              data = deu, returnCumulative = TRUE)
aLev_psl



#--------------------------- 1) Data Manipulation ------------------------------

# 1.1) Subsets

# Age only between 25 and 65
# Test Language same as Native Language OR Language spoken most often at home
# only people with paid work experience
# exclusion of people who were studying at the time of data collection
# Skill-Categories of work (excluding people who haven't worked for more than five years)


# Germany
sdf_deu <- subset(deu, 
                  (ageg10lfs >= 2 & ageg10lfs <= 5) & 
                    (homlang == 1 | nativelang == 1) & 
                    nopaidworkever == 0 & 
                    (c_q07 != 4) &
                    (iscoskil4 >=1 & iscoskil4 <=4))
dim(sdf_deu) # N=3586; Variables=1328

# Finland
sdf_fin <- subset(fin, 
                  (ageg10lfs >= 2 & ageg10lfs <= 5) & 
                    (homlang == 1 | nativelang == 1) & 
                    nopaidworkever == 0 & 
                    (c_q07 != 4) &
                    (iscoskil4 >=1 & iscoskil4 <=4))
dim(sdf_fin) # N=3831; Variables=1328

# Poland
sdf_pol <- subset(pol, 
                  (ageg10lfs >= 2 & ageg10lfs <= 5) & 
                    (homlang == 1 | nativelang == 1) & 
                    nopaidworkever == 0 & 
                    (c_q07 != 4) &
                    (iscoskil4 >=1 & iscoskil4 <=4))
dim(sdf_pol) # N=3797; Variables=1328

# USA 
sdf_usa <- subset(usa, 
                  (ageg10lfs >= 2 & ageg10lfs <= 5) & 
                    (homlang == 1 | nativelang == 1) & 
                    nopaidworkever == 0 & 
                    (c_q07 != 4) &
                    (iscoskil4 >=1 & iscoskil4 <=4))
dim(sdf_usa) # N=4413; Variables=1328


# 1.2) Creating an edsurvey.data.frame.list of all four countries
sdf_all <- edsurvey.data.frame.list(datalist = list(sdf_deu, sdf_fin, sdf_pol, sdf_usa),
                                    labels = c("deu","fin",
                                               "pol","usa"))
dim(sdf_all)
sdf_all


# Up until here everything workes out, then it starts getting complicated: 


# 1.3) Customize CutPoints (to three instead of Default six)

# 1.3.1) LITERACY
sdf_all_Cut <- achievementLevels(
  achievementVars = c("lit"),
  aggregateBy = NULL,
  data=sdf_all,
  cutpoints = c("Low" = 0, 
                "Average" = 226, 
                "High" = 326),
  returnDiscrete = TRUE,
  returnCumulative = FALSE,
  weightVar = NULL,
  jrrIMax = Inf,
  omittedLevels = TRUE,
  defaultConditions = TRUE,
  recode = NULL,
  returnNumberOfPSU = FALSE,
  returnVarEstInputs = TRUE
)
  # tried using this within recode above to "save" new CutPoints (didn't work)
recode=list(lit=list(from=c("0","1"),
              to="Low"),
     lit=list(from=c("2","3"),
              to="Average"),
     lit=list(from=c("4","5"),
              to="High"))


# 1.3.2) NUMERACY
sdf_all_Cut <- achievementLevels(
  achievementVars = c("num"),
  aggregateBy = NULL,
  data=sdf_all,
  cutpoints = c("Low" = 0, 
                "Average" = 226, 
                "High" = 326),
  returnDiscrete = TRUE,
  returnCumulative = FALSE,
  weightVar = NULL,
  jrrIMax = Inf,
  omittedLevels = TRUE,
  defaultConditions = TRUE,
  recode = NULL,
  returnNumberOfPSU = FALSE,
  returnVarEstInputs = TRUE
)

# 1.3.3) PSL / ICT
sdf_all_Cut <- achievementLevels(
  achievementVars = c("psl"),
  aggregateBy = NULL,
  data=sdf_all,
  cutpoints = c("Low" = 0, 
                "Average" = 226, 
                "High" = 326),
  returnDiscrete = TRUE,
  returnCumulative = FALSE,
  weightVar = NULL,
  jrrIMax = Inf,
  omittedLevels = TRUE,
  defaultConditions = TRUE,
  recode = NULL,
  returnNumberOfPSU = FALSE,
  returnVarEstInputs = TRUE
)

showCutPoints(data = sdf_all_Cut) # CutPoints haven't changed, Warning messages 


# Thoughts:
# cannot use recode-function since it is only meant for discrete variables, 
# thought GetData might be an Option but am afraid I might mess up the PVs and weights

# Tried different approach: 
# 1.4) Subset achievement levels

# Warning message: cannot find competencies as variables

# LITERACY
sdf_allM_Lit <- subset(sdf_all, 
                       (lit > 226 & lit < 325))
dim(sdf_allM_Lit) 

# NUMERACY
sdf_allM_Num <- subset(sdf_all, 
                       (num > 226 & num < 325))
dim(sdf_allM_Num) 

# PSL / ICT
sdf_allM_PSL <- subset(sdf_all, 
                       psl > 226 & psl < 325)
dim(sdf_allM_PSL) 

                       
# 1.5) Dummy-Coding 
# not specified yet

# 1.5.1) achievement levels
# would like:
# low = Level 0 & 1 (0-225)
# average = Level 2 & 3 (226-325)
# high = Level 4 & 5 (326-500)

# Germany as an example
# 1.5.1.1) LITERACY
summary2(sdf_deu,"lit", omittedLevels = TRUE) # removed omitted Levels via TRUE
logit1 <- logit.sdf(I(lit %in% c('226-325')) ~ ageg10lfs + gender_r + pared + edcat7 + b_q01b + j_q02a + j_q03a, 
                   data=sdf_deu,
                   weightVar = NULL,
                   relevels = list(),
                   varMethod = c("jackknife", "Taylor"),
                   jrrIMax = Inf,
                   omittedLevels = TRUE,
                   defaultConditions = TRUE,
                   recode = NULL,
                   returnNumberOfPSU = FALSE,
                   returnVarEstInputs = TRUE
)
summary(logit1)

# 1.5.1.2) NUMERACY

# 1.5.1.3) PSL / ICT


# 1.5.2) Categorial Variables

# Co-Variables: ageg10lfs + gender_r + nativelang + homlang
# QUESTION: How can I place these separately later in the analysis or do I also have to include them as normal predictors?

# Predictors (might have to narrow them down to 4-5 of interest?): 
  # c_q07 + iscoskil4 + pared + edcat7 + b_q01b + j_n05a2 + j_q02a + j_q02c + j_q03a + readytolearn_wle_ca
    # Skill Use: ICTHOME_WLE_CA, ICTWORK_WLE_CA, NUMHOME_WLE_CA, NUMWORK_WLE_CA, READHOME_WLE_CA, READWORK_WLE_CA, WRITHOME_WLE_CA, WRITWORK_WLE_CA



#--------------------------- 2) Check data / statistical requirements for Analysis ------------------------------



#--------------------------- 3) Statistical Analysis ------------------------------

# 3.1) Multiple Multivariate Regression

# Germany as an example (could also use data=sdf_all or do every country seperatly)
mvrlm.sdf(
 lit_low | lit_average | lit_high ~ ageg10lfs + gender_r + pared + edcat7 + b_q01b + j_q02a + j_q03a,
 data=sdf_deu,
 weightVar = NULL,
 relevels = list(),
 jrrIMax = Inf,
 omittedLevels = TRUE,
 defaultConditions = TRUE,
 recode = NULL,
 returnVarEstInputs = FALSE,
 estMethod = "OLS"
)


# 3.2) Multiple Linear Regression`
