### ISSUE TITLE
Best approach for mixed models with country-level data?

### ISSUE THREAD

**Issue by daparker26** [American-Institutes-for-Research/EdSurvey#5]
I am analyzing PIAAC data and want to create a multilevel model with countries. Currently, EdSurvey pulls PIAAC data from multiple countries into a list. However, mixed.spf only accepts edsurvey and light edsurvey data frames. I have tried to use getData() and rbind the light.edsurvey.data.frames into a single light.edsurvey.data.frame, but the attributes do not transfer and I'm unable to use rebindAttributes(), as my original data is from a list. Is there a best approach for doing this that I have missed? Or, do I need to go outside of the package? Thanks!

**Comment by pdbailey0** [comment]
@daparker26 this is a great question. We'll see if we can have any sample code that could help you.

**Comment by pdbailey0** [comment]
For now, the only way I see is for you to run the models directly in `WeMix` with the `mix` function. 

Here I start you off, showing you how I would condense the data. I'm not commenting on how I would deal with weights in PIAAC, you are responsible for that.

```r
require(WeMix)
require(EdSurvey)

# run once:
# downloadPIAAC("~/")
piaac <- readPIAAC("~/PIAAC/Cycle 1/", countries = c("fin","can"))
rawpiaac <- EdSurvey::getData(data=piaac,
                              varnames=c("lit", "spfwt0", "gender_r", "varunit", "varstrat", "cntryid"),
                              omittedLevels=FALSE)
# make one file
singlepiaac <- do.call(rbind, rawpiaac)
# add a psu identifier
singlepiaac$unique_psu <- paste0(singlepiaac$varunit, ":", singlepiaac$varstrat)

# you will need to decide how to weight, I just put in some values so it will run
singlepiaac$w1 <- singlepiaac$spfwt0 # MAY NOT BE CORRECT
singlepiaac$w2 <- 1 # MAY NOT BE CORRECT
singlepiaac$w3 <- 1 # MAY NOT BE CORRECT

m1 <- WeMix::mix(pvlit1 ~ gender_r + (1|unique_psu) + (1|cntryid), data=singlepiaac, weights=c("w1", "w2", "w3"))
summary(m1)
```
This makes results for a single replicate weight. You would need to estimate it again and estimate the imputation variance using the usual function, where beta is the estimate averaged over all plausible values and beta-sub-p is the estimate for an individual set of plausible values. You would want to add that to the variance estimate from any individual run, or the average variance estimate across all the runs.

![image](https://user-images.githubusercontent.com/14575300/126677212-2608afd9-2843-4c21-888d-647593690ff2.png)

I realize this isn't as easy as a call to `mixed.sdf`!

**Comment by daparker26** [comment]
Thank you so much for your response, Paul! I assumed I would need to go straight to WeMix. I appreciate the example.
