### ISSUE TITLE
 Issue with getData/rebindAttributes on TALIS data

### ISSUE THREAD

**Issue by AndersAstrup** [American-Institutes-for-Research/EdSurvey#53]
---
Hello

I am working with some TALIS 2018 data, and I can't analyze data that I have manipulated with getData + rebindAttributes. Seems to me that the issue is related to a check of attributes of plausible values , which there are none of in TALIS 2018.
 
I am wondering if there is an easy way to fix this, or to bypass that check for plausible values, if i am correct that this is the source of the issue?

Below is a few lines of codes that should reproduce the issue.

Thank you all for the work on EdSurvey
/Anders

```r
library(EdSurvey) #version 3.1.0
#Load data
usa <- readTALIS(getwd(), countries = "usa", isced = "b", dataLevel = "teacher")
#Call getData with a few variables
usadata <- getData(usa,varnames = c("tc3g01","t3clain","tchwgt"))
#Rebind attributes
usa2 <- rebindAttributes(usadata,usa)
#analysis of this object gives error "Error in getAttributes(data, "pvvars") : Attribute pvvars not found."
lm.sdf(t3clain~tc3g01,usa2)
#It does not give any error with the original object
lm.sdf(t3clain~tc3g01,usa)


```

sessionInfo()
```r
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=Danish_Denmark.utf8  LC_CTYPE=Danish_Denmark.utf8    LC_MONETARY=Danish_Denmark.utf8
[4] LC_NUMERIC=C                    LC_TIME=Danish_Denmark.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] EdSurvey_3.1.0 Dire_2.1.1     lfactors_1.0.4 car_3.1-2      carData_3.0-5 
```

**Comment by pdbailey0** [comment]
Just FYI, we're still looking at this. I think we'll need to make a new version of EdSurvey.

**Comment by pdbailey0** [comment]
Try installing the development version now. It should be fixed.
```
# You can install the development version from GitHub with:
install.packages("devtools")
devtools::install_github("American-Institutes-for-Research/edsurvey")
```
See NEWS item as well https://github.com/American-Institutes-for-Research/EdSurvey/blob/main/inst/NEWS.Rd#L11

Thanks, again, for reporting this.

I'm closing this, but feel free to reopen it if there is a problem

**Comment by pdbailey0** [comment]
@AndersAstrup sorry about that. I think I fixed it now. I just tested and it worked for me.
