### ISSUE TITLE
Query Regarding SEM Package for NAEP Data

### ISSUE THREAD

**Issue by nirmalghimire** [American-Institutes-for-Research/EdSurvey#54]
Dear AIR Researcher Team,

I hope this message finds you well. I am writing to request assistance with SEM in the EdSurvey package. Specifically, I am interested in conducting a study using PISA 2018 data, in which we want to see how selected student and school level variables impact students' test scores in science, math, and reading. We are also interested in exploring the variability of impact based on the subjects, as well as the correlation between the variables.

Dr. Zhang kindly replied to my previous email saying that the EdSurvey package may not have the features that we need for our study. However, she also expressed the willingness to assist us in any way possible. Therefore, I am reaching out to your team for any guidance and support in conducting our SEM model in the PISA 2018 data.

Thank you for your time and attention to this matter. I look forward to hearing back from you soon.

Best regards,
Nirmal Ghimire

**Comment by pdbailey0** [comment]
@nirmalghimire `EdSurvey` includes weighted mixed models from the `WeMix` package. Many (but far from all) SEM can be fit in this context. This is available in `EdSurvey` in the `mixed.sdf` function. There are many SEM packages in R as well that you can use.
