### ISSUE TITLE
PIRLS 2021

### ISSUE THREAD

**Issue by njaalf** [American-Institutes-for-Research/EdSurvey#56]
Hi, are there any plans to accomodate PIRLS 2021 analysis in EdSurvey?

I have managed to open the 2021 data, after a few quick fixes, but I still have problems setting the number of jackknife replicates.
It is supposed to be 250 in PIRLS 2021, I believe.  EdSurvey has 160 JK replicates as default. 

Is it EdSurvey that generates the JK replicates?

It would be nice if EdSurvey could fully support working with PIRLS 2021. The data came out in may 2023, so I guess people are doing data analysis currently.

**Comment by pdbailey0** [comment]
@njaalf we just added PIRLS 2021; try installing the 4.0.4 from github

```
# You can install the development version from GitHub with:
install.packages("devtools")
devtools::install_github("American-Institutes-for-Research/edsurvey")
```
