### ISSUE TITLE
readTIMSS() did not merge teacher data correctly when dealing with the eighth grade data in TIMSS 2019

### ISSUE THREAD

**Issue by RedGinger1994** [American-Institutes-for-Research/EdSurvey#66]
Hi,
I just tried to retrieve the merged data through readTIMSS(), but found that teacher data were omitted. For reproducing the problem, I attached the following codes for your replications. 

TIMSS19.8 <- readTIMSS(path = "../TIMSS/2019/TIMSS/2019", countries="HKG", gradeLvl = "8",forceReread = TRUE)
data.without.omit <- getData(data = TIMSS19.8,
                             varnames = c("btbg01"), #btbg01 is GEN\YEARS BEEN   TEACHING
                             dropOmittedLevels = FALSE,
                             returnJKreplicates=FALSE)

The error message is as following:
Error in getData(data = TIMSS19.8, varnames = c("btbg01"), dropOmittedLevels = FALSE,  : 
  The following variable names are required for this call but not found in the data: ‘btbg01’.

I hope you could fix it. 
Thanks,

**Comment by pdbailey0** [comment]
It's telling you that variable is not on the data. When that happens you can search for it with `?searchSDF` here's an example from that function's documentation
```
# read in the example data (generated, not real student data)
sdf <- readNAEP(system.file("extdata/data", "M36NT2PM.dat", package="NAEPprimer"))
# search both the student and school files by a character string
searchSDF(string="book", data=sdf)
```
Searching I found that variable is present and has a math and science version with suffix that distinguishes them.

I hope that helps.
