### ISSUE TITLE
EdSurvey with country dataset

### ISSUE THREAD

**Issue by tzhangumd** [American-Institutes-for-Research/EdSurvey#69]
Subject
EdSurvey with country dataset

Message
I am working for the Czech School Inspectorate and the Czech Ministry of Education as data analyst. I would like to kindly ask you, if EdSurvey package in R is able to analyze custom PISA/TIMSS/PIRLS data frames since I have data on these surveys in SPSS sav formate. Usually, I marge students and teachers questionnaires data into single dataset via key identifier. Will edSurvey work? In the book I have not found any instruction if the data are not downloaded via the package. I am struggling to run HLM model with plausible values and replication weights in R as recommended in manuals and academic literature. IDB analyses can comprehend only basic statistics and is not useful. Also, I am not familiar with Plus, but I do statistical analysis exclusively in R software. 
Thank you very much for any help how to properly run a HLM model using R with all requirements on plausible values, weighting and replications.
Kind Regards
Jakub Lysek

**Comment by pdbailey0** [comment]
Dr. Lysek, you would need to use the files that are published by IEA (TIMSS/PIRLS) or OECD (PISA). EdSurvey would merge them for you automatically and allows you to add or edit variables and then run a weighted HLM with `mix.sdf`
