### ISSUE TITLE
error in getData for multiple countries

### ISSUE THREAD

**Issue by joaomaroco** [American-Institutes-for-Research/EdSurvey#71]
Hi Paul,

I am having trouble in getting the getData function to work with given variables names, returning an error saying that the variables are not in the edsurvey dataframe. Here is what I did:

Download all TIMSS 2019 grade 8 files from TIMSS & PIRLS ISC

1, Made a vector of countries:
`cnt <- unique(t8s$IDCNTRYL)`
`cnto <- cnt[-which(cnt %in% c("Dubai,UAE","Abu Dhabi, UAE","Moscow City, Russian Fed.","Canada, Ontario","Canada, Quebec"))]`
#convert to 3 digits ISO codes
`cntc <- countrycode::countrycode(cnto, origin = "country.name", destination = "iso3c", custom_match = c('England' = 'GBR'))`

2. `Read the data into edsurvey with dbESt8 <- EdSurvey::readTIMSS(path = dir, gradeLvl = 8, countries = cntc)`

3. Made a list of TIMSS 2019 student variables as
`stdvars <- c("BSBG01", "BSBGHER", "BSBGSB", "BSBGSLS", "BSBGICS", "BSBGSCS", "BSBGSVS", "BSBGSEC", "BSDG05S", "BSDGEDUP")`

4. Read the data with:
`dat <- EdSurvey::getData(data = dbESt8,   varnames = c(stdvars),  dropOmittedLevels = TRUE, addAttributes = TRUE)`

I get the error:
`An error occurred while working on a dataset. Excluding results from this dataset. The following variable names are required for this call but not found in the data: ‘BSBG01’, ‘BSBGHER’, ...
...
  The argument ‘data’ must be an edsurvey.data.frame or a light.edsurvey.data.frame.`

I wonder if creating a list of all countries' data with `readTIMSS` is not compatible with `getData`? And one has to do it country by country?

Thanks in advance!

**Comment by pdbailey0** [comment]
@joaomaroco it's saying it can't find those variables. EdSurvey converts variables from the provider to lower case, so try doing that to your variables

```r
 dat <- EdSurvey::getData(data = dbESt8,   varnames = tolower(stdvars),  dropOmittedLevels = TRUE, addAttributes = TRUE)
```

this code works for me
```r
cntc <- c("USA", "Fra")
dir <- "~/your path to the TIMSS 2019 data"
dbESt8 <- EdSurvey::readTIMSS(path = "~/EdSurveyData/TIMSS/2019/", gradeLvl = 8, countries = cntc)
dat <- EdSurvey::getData(data = dbESt8,   varnames = tolower(stdvars),  dropOmittedLevels = TRUE, addAttributes = TRUE)
# dat[[1]][[1]] now has the us data in it, dat[[1]][[2]] has the French data in it
```
I hope that helps! Feel free to reopen if you continue to have issues.

**Comment by joaomaroco** [comment]
Thanks Paul...
I missed the conversetion to lowercase
But, anyway, I want to run a HLM with 3 levels (std, schools and countries) but the getData for all countries returns a list not a dataframe as mixed.sdf requires:

l0 <- mixed.sdf(formula = bssci0 ~ 1 + (1|cntschid) + (1|idcntry),
  weightVar=c("w_fstuwt", "w_fschwt"),
  data = dat$datalist, weightTransformation = FALSE)
summary(l0)



Error in checkDataClass(data, c("edsurvey.data.frame", "light.edsurvey.data.frame")) :
  The argument ‘data’ must be an edsurvey.data.frame or a light.edsurvey.data.frame.


Is there a way to convert a edsurvey list in a dataframe?


Thanks!
Jº
________________________________

**Comment by pdbailey0** [comment]
@joaomaroco ah, you want to combine them into one. You can do that, but that was not a goal of EdSurvey, so you'll have to write a loop or something to accomplish that. At that point, you're outside of EdSurvey and you'll need to write your own code to combine PVs.

**Comment by joaomaroco** [comment]
🙁
Warm regards,
João
________________________________

**Comment by joaomaroco** [comment]
Hi Paul,
Is there an easy way to find the fixed effects variance and random effects variance from WeMix? I need to calculate the Conditional R2 and Marginal R2, but I am kind of lost in the WeMix object.
Thanks
João Marôco
________________________________

**Comment by pdbailey0** [comment]
@joaomaroco  this is a new issue, please click the "new issue" button when you have a new question.
