### ISSUE TITLE
Appending factor scores to a dataset.

### ISSUE THREAD

**Issue by atkirakosian** [American-Institutes-for-Research/EdSurvey#76]
**Is your feature request related to a problem? Please describe.**
Unsure. The potential problem I experienced was trying to use a dataset I created with NAEPEX which then included factor scores generated through Mplus. 

**Describe the solution you'd like**
An EdSurvey feature that would allow for confirmatory factor analyses that generate factor scores, and then append said factor scores into the data frame or class that is specific to EdSurvey. 

**Describe alternatives you've considered**
I used the lmer (lme4 package) and lm (stats package) syntax in R. 

**Additional context**
We used EFA and CFA on NAEP data to generate factor scores related to teaching and remote instruction from the 2022 NAEP Math Assessment. EFA was done in SPSS and CFA done in Mplus. For the analyses run in R, we were only able to include the original weight variable instead of the original and replicate weight variables. I know EdSurvey accounts for all this behind the scenes so, being able to get factor scores and append them via EdSurvey would be ideal.

**Comment by pdbailey0** [comment]
@atkirakosian thanks for your interest in EdSurvey. Are you hoping to merge on these factor scores? or what is your intended work flow?

**Comment by atkirakosian** [comment]
@pdbailey0 if I understand correctly, yes. A little more context is warranted: we have 4 items contributing to a factor and our three other factors follow this trend as well. We reduced the dataset from multiple records per teacher to a single record per teacher and then we generated factor scores at the teacher level via Mplus. After that, we did a one-to-many merge through SPSS. With this dataset, we would like to assess some hierarchical linear models or step-wise regressions.

**Comment by pdbailey0** [comment]
You could use `merge`. Make sure the edsurvey data frame is the first argument in the merge call. 

I'll use the NAEP Primer, which doesn't have a good merge variable, but I'll use the teacher-level variable `yrsexp`, which is a weird example, but it shows the code.

```
# read in the NAEP Primer
sdf <- readNAEP(path=system.file("extdata/data", "M36NT2PM.dat", package = "NAEPprimer"))
# make up data to merge it to
df <- data.frame(yrsexp=c("0-4 years", "5-9 years", "10-19 years", "20+ years", "Omitted"), assignment=LETTERS[1:5])
df
#        yrsexp assignment
# 1   0-4 years          A
# 2   5-9 years          B
# 3 10-19 years          C
# 4   20+ years          D
# 5     Omitted          E

# merge on yrsexp variable, you'll want to use an ID here
newsdf <- merge(sdf, df, by="yrsexp", all.x=TRUE,all.y=FALSE)
# check that it worked
table(newsdf$assignment, newsdf$yrsexp)
#    
#     0-4 years 5-9 years 10-19 years 20+ years Omitted
#   A      3154         0           0         0       0
#   B         0      3435           0         0       0
#   C         0         0        4432         0       0
#   D         0         0           0      3976       0
#   E         0         0           0         0      94
```
I hope that helps.

**Comment by atkirakosian** [comment]
Thank you for providing this syntax! I tried it, but it didn't work. I think the merge feature is resulting in an error since our dataset is a subsample (i.e., 50% of cases randomly selected for CFA). Is there a way I could read our manipulated dataset into EdSurvey and use only that dataset for the analyses? The last time I tried that, it didn't seem to like the format, probably due to the new variables we created... or I was doing something wrong.

**Comment by pdbailey0** [comment]
@atkirakosian I would use an ID variables provided on the original data. You could even merge it on. If the data are teacher-level, you could just add that variable you created to the dataset using `$<-` 
```
sdf <- readNAEP(path=system.file("extdata/data", "M36NT2PM.dat", package = "NAEPprimer"))
sdf$psu_dsex <- paste(sdf$scrpsu, sdf$dsex, sep=":")
head(sdf[[c("scrpsu", "dsex", "psu_dsex")]]) # shows this worked
```
I hope that helps. EdSurvey isn't designed for you to bring your own data, so this is how I would do it.

**Comment by atkirakosian** [comment]
@pdbailey0 This helps a lot. Thank you, Paul!
