### ISSUE TITLE
EdSurvey and NAEP 2017 Process Data

### ISSUE THREAD

**Issue by atkirakosian** [American-Institutes-for-Research/EdSurvey#80]
Is EdSurvey capable of analyzing the 2017 Process Data? I see on the EdSurvey website that it can work with NAEP data up to 2022, but was not sure if this included the Process Data.

**Comment by tzhangumd** [comment]
NAEP process data analysis is different from NAEP testing and survey data that require the consideration of complex sample and assessment designs. There are other packages and tools can be used for the process data analysis. You can contact [AIR NAEP Process Data Center](https://www.air.org/project/center-process-data) for more information.
